src/ast.rs
src/compile.rs
src/constants.rs
src/error.rs
src/internal_rep.rs
src/lib.rs
src/obj_class.rs

This PR fixes a lot of clippy warnings. Code is now much more idiomatic.
No functional change intended. The code still builds and all tests pass after these changes.

Fix clippy warnings

---

src/compile.rs

I have a unit test for this, but it depends on the @alias annotation to cause the error, and I am still implementing that.  So a unit test will follow in a future PR.

Continue on TypeInfo declaration errors to display them all

---

src/ast.rs
src/internal_rep.rs
src/parser.lalrpop

Nothing is actually done with these yet.  Future work will need to
override the default ordering assumptions.
In our existing docs, we have used this syntax extensively in
annotations, and (to my knowledge) never in function calls.  For
consistency, we should support both.
The near term need is to support this syntax in annotations.  A
follow-on PR will add actual support here.  Allowing these to work in
the parser allows annotations that have no behavior defined yet, but use
the "name=foo" syntax to at least parse correctly.

Support named args passing with "name=foo" in parser

---

doc/resource_association.md

The previous example misused the "this" keyword to refer exclusively to
the original type.  Fix it to use the type name directly and add a note
clarifying the distinction.

Fix resource association example in docs

---

Cargo.toml
src/bin/casc.rs

Switch to new Derive API with more intuitive syntax.
This updates the -h output slightly.  The content is the same, but the
formatting is slightly different and reordered.  It also displays
colored output now.

Update to clap version 3

---

src/ast.rs
src/lib.rs
src/parser.lalrpop

When we encounter an error, we skip until the start of the next
annotated expression and continue.  If any errors were encountered, we
report and fail the build.
This enables displaying all parse errors at once rather than one at a
time.

Add error recovery to parser

---

src/lib.rs

"whereas" sounds unnatural in this error message.

Fix error message grammar

---

Cargo.toml
src/compile.rs
src/error.rs
src/internal_rep.rs

This makes internal errors debuggable.
This relies on the backtrace crate, as opposed to std::backtrace, which
is only available in nightly.  This causes issues with thiserror, which
if it sees a type named "Backtrace" assumes it must be
std::backtrace::Backtrace, and then fails to compile on stable.  Simply
renaming backtrace::Backtrace seems to work around this.

Include a backtrace on internal errors

---

src/compile.rs
src/internal_rep.rs

Updating to Clippy version 0.1.62 gives new borrow_deref_ref and
unnecessary_to_owned warnings that weren't seen on previous clippy
versions.

Fix new clippy warnings

---

tools/update-expected-cil.sh

Prior to commit 60668b87943cd8e4102a53650f561d1e6c7bc0d4, casc would
create a cil output file unconditionally, resulting in an empty file in
the event of a compilation failure.  That commit moved the logic to only
create an output file upon successful compilation.
The new behavior is obviously better, but tools/update-expected-cil.sh
had an implicit bad assumption that out.cil would always exist after a
compilation attempt, and attempt to remove it.  Since the script sets
-e, a failure to cleanup fails the script.
Fix the script to redirect cleanup errors to /dev/null and always return
true on cleanup.

Silently ignore cleanup failures when updating golden results

---

data/expected_cil/filecon.cil
data/policies/filecon.cas
src/internal_rep.rs
src/lib.rs

The "any" keyword makes a file context match any object class. Previously, this was supposed to be indicated by the empty string, but that didn't actually make any sense, because it's in an unquoted context and whitespace is skipped by the lexer, so there's no actual way to indicate an empty string file context.
Fix this by using the keyword "any" (the new Cascade keyword now matches the CIL keyword with the same purpose).
Also, expand the file_context test to test the any keyword

Fix handling of the "any" keyword in file contexts

---

Cargo.toml
src/bin/casc/args.rs
src/bin/casc/main.rs
src/error.rs

Detect whether we are writing to a terminal and conditionally enable color on error output
I had assumed termcolor did this for us, but according to their documentation, they do not, and recommend using the atty crate for this purpose: https://docs.rs/termcolor/latest/termcolor/#detecting-presence-of-a-terminal
The approach in this commit lets casc determine whether or not to use color, and then error.rs translates that boolean decision into the appropriate termcolor commands.  Casc makes its decision in turn based on atty detecting a terminal.  This architecture allows for future binaries to make different decisions if needed (eg a --nocolor flag).
Reported-by: Matthew Sheets <masheets@linux.microsoft.com>

Detect whether we are writing to a terminal and conditionally enable color

---

doc/policy_composer.md

* Add syntax examples
* Remove mention that traits are future work (they have now been implemented)
* Split paragraphs
* Simplify wording around virtual modules

Improve module and system documentation

---

Cargo.toml
src/bin/casc/args.rs

I was expecting this to be much more difficult than it turned out to be.  Back when 3.2.2 first was released, we hit a bunch of warnings, as described in this clap issue: https://github.com/clap-rs/clap/issues/3822.  Clap moved those warnings behind the "deprecated" feature flag in v3.2.3.  I was expecting to need to address the warnings I saw when updating to clap 3.2.2 before updating to v4, however those warnings seem to no longer occur.  Perhaps they were accidentally addressed as we generally updated our CLI based on online docs?  Or perhaps something changed on the clap end?
Regardless, updating clap and clap_mangen in concert, and fixing the one `_`/`-` confusion in the commit seems to have everything working functionally as far as I can tell.
As a future note, the clap migrating …

Update to clap v4

---

data/expected_cil/permissions.cil
src/lib.rs
src/obj_class.rs

The Vec being returned is turned into a list, so wrapping "all" in parentheses results in a list inside a list.  That behavior is supported by CIL, so it compiles, but the extra parentheses are unneeded.
Reported-by: Dominick Grift <dominick.grift@defensec.nl>

Drop extra parentheses around "all" in permission set.

---

src/bin/casc/package.rs
src/lib.rs

This doesn't add much infrastructure for this yet.  That is intentional, as user configuration isn't yet supported.  We'll need to add that infrastructure later, once we add UBAC support to Cascade.

Add an seusers file

---

src/compile.rs
src/error.rs
src/internal_rep.rs
src/lib.rs

Previously, if an error was reported based on internally generated code, an error would be reported without referencing a code point, which isn't actionable.  This series changes that situation to an internal error, and cleans up several internal error situations so that they accurately point to a code point.
In general, we should not be reporting errors directly on internally generated code.  Our error messages should point directly at the source the user wrote that triggered the compile error.

Clean up error handling to avoid error messages without code points

---

src/context.rs
src/internal_rep.rs

Previously context lookups were done on string slices instead of CascadeStrings, meaning that returning the looked up value required constructing a new CascadeString with None range.  Instead, have them take CascadeStrings, so if the lookup fails, we can just return the full CascadeString with its range.
closes #92

Fix bug where context lookups discarded the range

---

.github/workflows/clippy.sh
.github/workflows/doc.sh
.github/workflows/format.sh
.github/workflows/restore-checks.sh
.github/workflows/rust.yml

Clippy regularly updates with new checks.  When this happens, we update our repo to account for this (either fixing the code, or disabling the checks).  However, this often hits a new PR that happens to be the first PR to run against the new check.  That PR doesn't necessarily introduce an issue, but fails anyways.
Split the style checks to run against an older known good version of the toolchain, which can fail PRs, and also informationally run against the latest toolchain.  This way, PRs won't block on new clippy checks, but we'll still be notified of the need to fix them.
Once we fix the latest clippy checks, we can update the known good version to the new clippy version and continue checking against that version.
Clippy is the specific example here, but this updates the toolchain for …

Run PR failing style checks only on a known good toolchain version

---

data/error_policies/let_invalid_type.cas
data/expected_cil/let.cil
data/policies/let.cas
src/compile.rs
src/context.rs
src/functions.rs
src/internal_rep.rs
src/lib.rs

The symbol table should nest within blocks and do shadowed lookups.  This enables the removal of the special handling for global bindings, which was pretty broken.

Allow context nesting

---

.github/workflows/rust.yml

Rust has released the new 1.67 toolchain and it introduces no new clippy failures on our main branch

ci: Bump known good clippy to 1.67

---

src/lib.rs

The TODO item was addressed in 69c1586e7f1c9eb01da773e4cc4ce3ba5eddcbba, but the TODO comment wasn't removed

Remove already addressed TODO in trait_test()

---

.github/workflows/comment.yml

github-script version 5 introduced a breaking update
that moved where listWorkflowRunArtifacts & downloadArtifact
live.

Fix issue with github script version update

---

src/lib.rs

What happened was:
1. We had a bug that our errors were reversed
2. I incorrectly thought it was a parser issue
3. I reversed the parse error order to address it
4. Some time later, I found and fixed the real bug
5. Now the reversing of parse errors reversed the newly correct order
Removing the parse error workaround should have all errors in the correct order now

Remove obsolete/incorrect parse error order workaround

---

data/error_policies/bad_allow.cas
src/context.rs
src/functions.rs
src/internal_rep.rs
src/lib.rs

Previously on object classes with "2" (e.g. capability2) if a permission was not part of that object class the compiler would always report the 2nd object class.  Now the correct object class from the cascade policy should be reported.
Issue #76

Bad Perms report for correct object class

---

data/expected_cil/filecon.cil
data/expected_cil/fs_context.cil
data/policies/filecon.cas
data/policies/fs_context.cas
src/ast.rs
src/functions.rs
src/internal_rep.rs
src/parser.lalrpop

Previously, only bare types were accepted as contexts.  This change allows the specification of the full context.

Handle full contexts correctly

---

data/policies/let.cas
src/context.rs

This doesn't test usage, because I'm not sure these are actually usable anywhere.  I think we probably will need to enhance AVRules to support lists of classes, but that's a separate/future problem.

Store classlist bindings as classlists

---

src/ast.rs
src/functions.rs

Avoids uneccessarily copying all the FuncCall structs and is more usable

Convert get_all_func_calls to work with slices and references

---

data/policies/derive.cas
src/functions.rs

Annotations by design should be less strict about type checking

Automatically coerce single arguments to lists in annotations

---

.github/workflows/rust.yml

Since 3.5 is out of rcs, run our nightly checks against the latest and greatest.

Bump github actions check from 3.5-rc3 to 3.5.

---

src/compile.rs
src/internal_rep.rs

However, don't report derive errors on synthetic types - we should have reported the error on the parent

Don't short circuit on reporting derive errors, rather report them all

---

data/expected_cil/derive.cil
data/policies/derive.cas
src/ast.rs
src/compile.rs
src/functions.rs

Originally, derive_functions() was located inside validate_functions() after the function bodies were validated.  The intent behind this was that we first ensure that the parents are correct, before generating a possibly incorrect child.  Unfortuantely, that doesn't actually work because the parents may call derived functions, and would then fail validation because the derived function doesn't exist yet.
In order to address this, pull derive_functions() out of validate_functions() and put it earlier.  With this change the derived functions get set for prevalidation (so they are castable), and are available when validating the bodies of all functions.
This requires moving all the rename logic from ValidatedStatements to Statements, which is the bulk of the diffstat on this commit.
It also …

Move derive_functions() to before prevalidate_functions()

---

.github/workflows/clippy.sh
src/compile.rs

1. IMHO this suggestion typically makes the code less readable.  I find the interior if logic clearer than locating a flatten() in the middle of a chained collection of iterator calls and recalling the semantics of flatten() on an iterator.
2. The code suggestions provided by clippy to fix this issue do not always seem to compile.  I got #159 to compile and make clippy happen, and the flattening feels readable enough there, but the finally compiling code does not match clippy's suggestion, which was broken.
(In #159 I appeared to be running into something essentially similar to https://github.com/rust-lang/rust-clippy/issues/6893, but according to that issue, it was fixes a few years ago, so I'm not sure what's going on.  I might dig into it more, but as mentioned in point 1, I'm …

Ignore clippy manual_flatten errors

---

src/compile.rs
src/functions.rs
src/internal_rep.rs

This was used for the special handling of global symbol binding.  That has sense been rolled into the generic symbol binding code, but the BoundTypeInfo code wasn't removed.  Only the Unbound variant was even being used, and this was just dead code.

Remove dead BoundTypeInfo code

---

src/alias_map.rs
src/functions.rs
src/internal_rep.rs
src/machine.rs

Use this to look up only functions from a specific type, rather than all functions

[RFC] Add ability to do lookups on secondary indices in alias maps

---

src/compile.rs
src/internal_rep.rs

Use it for later lookups.
Callgrind reports is_child_or_actual_type() as a hot spot in the code, with is_resource() being the main caller.  This change aims to short circuit these calls by precomputing whether a type is a domain or resource and simply returning that instead of recursive calling every time.
Full system compile     time:   [12.402 ms 12.423 ms 12.451 ms]
change: [-0.5263% -0.1668% +0.1473%] (p = 0.36 > 0.05)
No change in performance detected.
Found 6 outliers among 100 measurements (6.00%)
4 (4.00%) high mild
2 (2.00%) high severe
Benchmarking Stress functions: Warming up for 3.0000 s Warning: Unable to complete 100 samples in 5.0s. You may wish to increase target time to 131.0s, or reduce sample count to 10.
Stress functions        time:   [1.3251 s 1.3334 s 1.3420 s] …

Save the variant (domain or resource) of a type at creation time

---

data/expected_cil/casting.cil
data/policies/casting.cas
src/functions.rs

There may still be an issue if we're casting from a type passed in as an argument, but that seems like a bigger problem that deserves its own separate PR.

Fix bug where "this" wasn't resolved when casting from it.

---

data/error_policies/class_wrong.cas
src/functions.rs
src/lib.rs

The error message should be returned pointing to the actual string the user entered, not the name of the type we resolved it to, which may by built in or synthetic.  The non-list case had this correct, but the list case was wrong

Fix internal error when validation fails on items in lists

---

Cargo.toml
src/bin/casc/main.rs

The atty crate appears abandoned and has a known security issue.  See https://rustsec.org/advisories/RUSTSEC-2021-0145 for more details on the issue.
The security issue is Windows only, and can only occur in certain situations under the control of our code, however, the crate is unmaintained and migration to a reasonable alternative is simple.

casc: Migrate from atty to is-terminal

---

Cargo.toml

See comment in Cargo.toml for details.  This should be reverted once lalrpop publishes a fix

Add a temporary regex_syntax dependency to work around breakage

---

Cargo.toml

This was actually already released when we added criterion, but the criterion user guide still pointed to 0.3.  Criterion updated their guide to mention 0.4 after the 0.4 release.
"Cargo bench" still works fine for our use case on the new version, and the measured performance numbers seem stable.

Bump criterion version to 0.4

---

data/expected_cil/permissions.cil
data/policies/permissions.cas
src/context.rs
src/functions.rs
src/internal_rep.rs

https://github.com/dburgener/cascade/pull/199 caused some of our type matching on lists to start to fail.  First clean up the error message when this happens, which was previously a TODO, then try harder to infer the right types.  As mentioned in the second commit message, this has us guess (possibly wrongly) on ambiguity.  For a post-0.1 future enhancement, we should detect ambiguity and require the developer to annotate.

Clean up type validation on lists

---

data/expected_cil/makelist.cil
data/policies/makelist.cas
src/lib.rs

This test was disabled because of a bug around functions that has since been fixed

Reenable makelist test

---

data/error_policies/invalid_default1.cas
data/error_policies/invalid_default2.cas
src/functions.rs
src/lib.rs

The previous code had a note about errors being potentially confusing, and boy was that note accurate.  We were mixing the caller's range with the declarer's file, and ending up pointing to a nonsense code point in the declarer's file, and claiming that a random portion of a comment wasn't a valid type.
The real solution here of course is to store file ids in CascadeStrings and then every CascadeString will have its file and range together as one chunk, but that's a pretty major rewrite, that will need to happen after 0.1

Use the right file when validating default arguments

---

data/error_policies/error_in_associate.cas
data/expected_cil/associate.cil
data/policies/associate.cas
src/compile.rs
src/lib.rs

These would either be calls which apply anyways because of the parent child relationship, or things like file_context() that would error when inherited.
The real problem with these is that in certain scenarios they can result in the same statement being validated twice, once with a file and once without, and if it has an error, it is a problem

Don't have synthetic resources inherit statements from their parents

---

src/lib.rs

It looks like they became backwards in a bad merge resolution.  This commit makes the test function names refer to the files of the same name

Swap this_casting and casting test names

---

data/error_policies/alias_conflict.cas
src/alias_map.rs
src/compile.rs
src/error.rs
src/functions.rs
src/lib.rs

The first commit is just a minor reordering to 1. Prepare to totally rewrite search_for_recursion() on top of the call tree added recently and 2. Delay the performance hit associated with it until later, in case there are errors earlier in compilation.
The second commit turns the infinite loop we were seeing on alias conflicts into an internal error.  This should help detect any future bugs in this area more easily.
The final commit is the real fix, which checks for alias conflicts and reports an error.  The error handling is an extremely awkward dance with a performance hit, as described in the commit message.  We should get everything back in terms of both code complexity and performance once we implement #219.

Fix infinite loop bug(s) in recursion checking

---

src/ast.rs
src/compile.rs
src/machine.rs

* It is less error prone if explicit PartialOrd implmenentations call cmp() directly rather than reimplementing the same user logic in terms of partial_cmp()
* Don't use into_iter() on a function that takes IntoIterator

Fix issues reported by nightly version of clippy

---

src/parser.lalrpop

The regex tokens "\s" and "\d" are "unicode friendly" and could match whitespace and digit characters in other encodings than ASCII.  The result of including them in our grammar is that we then require regex support for the entirety of unicode, which builds a large table of unicode characters into our binary.
Replace \s and \d with their ASCII-only equivalents, [[:space:]] and [[:digit:]].
Note that this does not remove our unicode dependency by itself. Lalrpop 0.19.12 builds in unicode support by default because it doesn't yet expose the correct configuration knobs to users to enable or disable unicode support.  Once lalrpop 0.20 is released, then users that don't require unicode support will be able to disable it using a feature. This change moves Cascade to that "users that don't …

Drop unicode aware regexes

---

src/lib.rs

The initial implementation assumed that PolicyParser::new() was a relatively cheap function time-wise, and called it once per file. There's no need to rebuild it, and it turns out in lalrpop performance discussions that new() can actually be expensive (and possible performance improvements could move work into new() to speed up the steady state).
Regardless of the significance, there's no real cost to pulling new() out to call once per file (although it might complicate the API ever so slightly if we later expose parse_policy() as a public function.)
The benchmark run is below.  The weird thing is that Stress Functions only has one file, so I would expect this to be a no-op for performance there.  But that 14% has been pretty reproducible across multiple runs. I'm not really sure what's …

Only build the parser once

---

Cargo.toml

* Finally get obsolete, unmaintained atty crate out of our dependency tree
* Unify on clap 4 (we had 4, but criterion 0.4 had 3)

Update to criterion 0.5

---

Cargo.toml

This feature enables support for unicode regexes, which we don't need. The extra unicode support bloats binary size and hurts performance

Do not use the lalrpop unicode feature

---

src/parser.lalrpop

The current code's skip pattern matches zero whitespace characters when skipping whitespace.  The result in the lalrpop lexer is that a zero-length match on no whitespace is found as a possible match.  In the common case where a longer match (the next token) was found, lalrpop discards the shorter match and returns the longer.  If no longer match was found, lalrpop has special handling to note that if only a zero-length match was found, that means no valid ones were.  So matching zero-length whitespace doesn't actually cause a problem, but it's also useless.
So write the expression we intend, which is to skip actual whitespace.

Don't skip non-existent whitespace

---

.github/workflows/rust.yml
Cargo.toml
src/functions.rs
src/internal_rep.rs
src/lib.rs

See commit descriptions for details

Various routine maintenance tasks

---

Cargo.toml

The _ variants of several Cargo fields will be deprecated in the 2024 edition.  Switch to the recommended - variants.
https://github.com/rust-lang/cargo/pull/13783

Use default-features in favor of default_features

---

.github/workflows/clippy.sh
src/bin/audit2cascade.rs
src/bin/casc/main.rs
src/lib.rs
src/test.rs

This creates a predictable experience for developers running "cargo clippy" locally.
Note that "uninlined_format_args" was allowed due to a clippy bug which has since been fixed, so that exception is no longer needed.

Move clippy overrides from the github actions code into the source

---

src/lib.rs
src/warning.rs

The first *paragraph* is used as the short summary in documentation, rather than the first *line* which is what the current code assumes. This makes the generated documentation create the correct short summary.

Add a blank line after the short summary in doc comments

---

build.rs

This alternative to process_root() was added in lalrpop 0.21 and searches only in the src directory for lalrpop files, rather than the entire project directory.

Use lalrpop process_src() helper function

---

.github/workflows/rust.yml

In addition to just moving this forward, which is good, this also eliminates breakage on building the home crate, which we inherit through lalrpop and term.  The home crate recently bumped its msrv to 1.81.

Bump known good clippy version to 1.83

---

.github/workflows/restore-checks.sh
.github/workflows/rust.yml
Cargo.toml

Also update CI to test it and ensure future compatibility

Set rust MSRV to 1.70
