dburgener/cascade

Cargo.toml
src/bin/casc.rs

Also support multiple files on command line

Implement command line parsing via clap crate

---

.github/workflows/clippy.sh
.github/workflows/rust.yml
src/ast.rs
src/internal_rep.rs
src/lib.rs

Fix one clippy issue and disable new_without_default

Add Clippy to CI

---

src/lib.rs

Convert existing error tests to use this macro
The macro takes the policy file, the expected error count, and a pattern
to match all errors against, and then verifies that the supplied file
produces the specified errors.

Add a macro for defining error tests

---

README.md

Include pointers to roadmap and changelog

Add project status section to README.md

---

.github/workflows/clippy.sh
src/ast.rs
src/compile.rs
src/lib.rs

This uses a slightly more permissive clippy configuration, since test
code doesn't need the same quality production code does.

Run clippy on tests

---

src/internal_rep.rs

The previous behavior took the range from the declaration.  This is wrong, since the string may be used in an error message about the current reference.  It also causes problems if the setype is built in, since in that case the range will be None

Return correct range in TypeInstance::get_name_or_string() for setypes

---

src/compile.rs
src/internal_rep.rs

On https://github.com/dburgener/cascade/pull/39 a number of small style issues were noted in PR review.  This fixes a few of them.

Some minor cleanups of @derive

---

data/policies/full_system/README.md
data/policies/full_system/all_files.cas
data/policies/full_system/base_resource.cas
data/policies/full_system/contexts/default_contexts
data/policies/full_system/contexts/virtual_domain_context
data/policies/full_system/contexts/virtual_image_context
data/policies/full_system/contexts/x_contexts
data/policies/full_system/general.cas
data/policies/full_system/kernel.cas
data/policies/full_system/machine_config.cas
data/policies/full_system/unconfined.cas
src/lib.rs

This policy provides a simple system policy which is bootable in enforcing mode on Fedora 36 and is useful for demonstrations and testing.

Introduce a simple sample policy

---

.github/workflows/rust.yml

Will bump to actual 3.5 once it's released

Add CI test for secilc 3.5-rc2

---

data/policies/conditional.cas
src/constants.rs
src/internal_rep.rs
src/lib.rs

Parse "true" and "false" as booleans.

Add bool built in type

---

src/error.rs

Errors were being displayed in reverse order of being found, which typically should occur in the order they are in the file.  This commit displays in them in the order found rather than reversing by iterating from the end of the list.

Display errors in the correct order

---

data/policies/conditional.cas
src/lib.rs
src/parser.lalrpop

Also expand boolean parsing test cases

Parse the "!" character in boolean expressions

---

data/expected_cil/associate.cil
data/policies/associate.cas
src/compile.rs
src/internal_rep.rs
src/lib.rs
src/parser.lalrpop

Writing the test case for this exposed a bug in nested association extension, so that's fixed in the first commit.

Allow the use of associated resources in contexts

---

src/functions.rs

There were a small number of bugs with the recursion detection which has been resolved as well as improvements with the error given to users

Fix recursive detection and related errors

---

src/ast.rs
src/functions.rs

If the function doesn't exist, provide more information about why not to aid the policy developer in debugging
(And to be fair, aid the compiler developer in debugging compiler errors as well :) )

Improve "No such function" error message

---

src/functions.rs

This allows for much more performant removals of items.
Stress functions        time:   [758.52 ms 774.47 ms 793.45 ms]
change: [-52.425% -50.936% -49.247%] (p = 0.00 < 0.05)
Performance has improved.

search_for_recursion: Switch term and nonterm lists to BTreeSets

---

src/functions.rs
src/internal_rep.rs

New warnings from nightly clippy 1.71

Remove some unused muts

---

src/functions.rs

Hopefully make them clearer and more actionable

Clean up recursion error messages

---

src/functions.rs

After subsequent refactoring, we no longer test the call and cast names separately.  We resolve first, then test.  So instead of looping, resolve, and if it doesn't exist, calculate the range to report on

Remove unecessary for loop

---

data/expected_cil/filecon.cil
data/policies/filecon.cas
src/internal_rep.rs

More complete genhomedircon support will be future work

Treat HOME_ROOT and HOME_DIR as paths

---

Cargo.toml
src/error.rs

* Latest version, will get fixes
* Proper fix for regex transitive dependency issues/unicode support
* Expecting big performance wins once 0.20.1 is released

Update to lalrpop 0.20

---

src/internal_rep.rs
src/machine.rs

Elide needless lifetimes
